- id: cpd
  name: cpd
  description: Checks for copy-pasting.
  language: docker
  entry: /bin/bash /usr/bin/run_cpd.sh
  files: \.java$
  require_serial: true

- id: check-no-tabs
  name: check-no-tabs
  description: Checks that no horizontal tabs are used.
  language: docker
  types: [text]
  entry: /bin/bash /usr/bin/check-no-tabs.sh
  require_serial: true

- id: check-eof-newline
  name: check-eof-newline
  description: Checks that all text files end with a newline.
  language: docker
  types: [text]
  entry: /bin/bash /usr/bin/check-eof-newline.sh
  require_serial: true

- id: check-trailing-whitespace
  name: check-trailing-whitespace
  description: Checks for trailing whitespace.
  language: docker
  types: [text]
  entry: /bin/bash /usr/bin/check-trailing-whitespace.sh
  require_serial: true

- id: checkstyle
  name: checkstyle
  description: Checks for code style violations.
  language: docker
  entry: /bin/bash /usr/bin/run_checkstyle.sh
  files: \.java$
  require_serial: true
