- id: cpd
  name: cpd
  description: "Runs the Copy/Paste Detector (CPD)."
  language: docker
  entry: /bin/bash /usr/bin/run_cpd.sh
  files: \.java$
  require_serial: true

- id: check-no-tabs
  name: check-no-tabs
  language: docker
  types: [text]
  entry: /bin/bash /usr/bin/check-no-tabs.sh
  require_serial: true

- id: check-eof-newline
  name: check-eof-newline
  description: Checks that all text files end with a newline.
  language: docker
  types: [text]
  entry: /bin/bash /usr/bin/check-eof-newline.sh
  require_serial: true

- id: check-trailing-whitespace
  name: check-trailing-whitespace
  description: Checks for trailing whitespace
  language: docker
  types: [text]
  entry: /bin/bash /usr/bin/check-trailing-whitespace.sh
  require_serial: true

- id: checkstyle
  name: checkstyle
  description: "Runs the Checkstyle static code analysis tool."
  language: docker
  entry: /bin/bash /usr/bin/run_checkstyle.sh
  files: \.java$
  require_serial: true
